---
kind: pipeline
type: docker
name: push-image

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: nytimes/golang-gcloud-sdk
    auto_tag: true
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event: [tag, push]
    branch: master
